export interface InitialLegalDocument {
  id: string;
  title: string;
  docNumber: string;
  agency: string;
  url: string;
  abstract: string;
  category: string;
  status: 'published';
}

export const INITIAL_LEGAL_DOCUMENTS: InitialLegalDocument[] = [
  {
    id: "luat-49-2024-qh15",
    title: "Luật Phòng không nhân dân số 49/2024/QH15",
    docNumber: "49/2024/QH15",
    agency: "Quốc hội",
    url: "https://vanban.chinhphu.vn/?docid=212477&pageid=27160",
    abstract: "Luật quy định về quản lý, điều hành và bảo vệ không phận quốc gia, quản lý tàu bay không người lái và phương tiện bay siêu nhẹ.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "nghi-dinh-288-2025-nd-cp",
    title: "Nghị định số 288/2025/NĐ-CP quy định về quản lý tàu bay không người lái",
    docNumber: "288/2025/NĐ-CP",
    agency: "Chính phủ",
    url: "https://vanban.chinhphu.vn/?classid=1&docid=215810&pageid=27160&typegroupid=4",
    abstract: "Quy định chi tiết về quản lý tàu bay không người lái và các phương tiện bay khác.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "thong-tu-146-2025-tt-bqp",
    title: "Thông tư số 146/2025/TT-BQP",
    docNumber: "146/2025/TT-BQP",
    agency: "Bộ Quốc phòng",
    url: "https://vanban.chinhphu.vn/?docid=216587&pageid=27160",
    abstract: "Quy chuẩn kỹ thuật và quy trình quản lý hoạt động bay thuộc thẩm quyền Bộ Quốc phòng.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "thong-tu-39-2025-tt-bqp",
    title: "Thông tư số 39/2025/TT-BQP",
    docNumber: "39/2025/TT-BQP",
    agency: "Bộ Quốc phòng",
    url: "https://vanban.chinhphu.vn/?classid=1&docid=214031&pageid=27160",
    abstract: "Hướng dẫn thực hiện quản lý, đăng ký và cấp phép phương tiện bay.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "nghi-dinh-36-2008-nd-cp",
    title: "Nghị định số 36/2008/NĐ-CP về quản lý tàu bay không người lái (Lịch sử)",
    docNumber: "36/2008/NĐ-CP",
    agency: "Chính phủ",
    url: "https://vanban.chinhphu.vn/default.aspx?docid=62937&pageid=27160",
    abstract: "Văn bản quy định khung quản lý tàu bay không người lái và phương tiện bay siêu nhẹ.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "nghi-dinh-79-2011-nd-cp",
    title: "Nghị định số 79/2011/NĐ-CP sửa đổi Nghị định 36/2008/NĐ-CP",
    docNumber: "79/2011/NĐ-CP",
    agency: "Chính phủ",
    url: "https://vanban.chinhphu.vn/default.aspx?docid=151535&pageid=27160",
    abstract: "Sửa đổi, bổ sung một số điều của Nghị định số 36/2008/NĐ-CP.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "thong-tu-35-2017-tt-bqp",
    title: "Thông tư số 35/2017/TT-BQP (Lịch sử)",
    docNumber: "35/2017/TT-BQP",
    agency: "Bộ Quốc phòng",
    url: "https://vanban.chinhphu.vn/default.aspx?docid=189273&pageid=27160",
    abstract: "Quy định về cấp phép bay cho tàu bay không người lái.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "chi-thi-02-ct-ttg",
    title: "Chỉ thị số 02/CT-TTg về tăng cường quản lý tàu bay không người lái",
    docNumber: "02/CT-TTg",
    agency: "Thủ tướng Chính phủ",
    url: "https://vanban.chinhphu.vn/default.aspx?docid=198854&pageid=27160",
    abstract: "Tăng cường công tác quản lý đối với tàu bay không người lái và phương tiện bay siêu nhẹ.",
    category: "Văn bản pháp luật",
    status: "published",
  },
  {
    id: "cambay-mod-gov-vn",
    title: "Cổng tra cứu khu vực cấm bay, hạn chế bay (Bộ Quốc phòng)",
    docNumber: "BQP Map",
    agency: "Bộ Quốc phòng",
    url: "https://cambay.mod.gov.vn/",
    abstract: "Hệ thống bản đồ tra cứu chính thức vùng cấm bay và hạn chế bay toàn quốc.",
    category: "Vùng cấm / hạn chế bay",
    status: "published",
  },
  {
    id: "huong-dan-cap-phep-bay-chinhphu",
    title: "Hướng dẫn thực hiện thủ tục cấp phép bay và tra cứu khu vực cấm/hạn chế bay",
    docNumber: "Chính phủ Guide",
    agency: "Cổng TTĐ T Chính phủ",
    url: "https://xaydungchinhsach.chinhphu.vn/huong-dan-thuc-hien-thu-tuc-cap-phep-bay-doi-voi-tau-bay-khong-nguoi-lai-va-cac-phuong-tien-bay-khac-119250616123043064.htm",
    abstract: "Hướng dẫn quy trình xin cấp phép bay chi tiết cho cá nhân và tổ chức.",
    category: "Vùng cấm / hạn chế bay",
    status: "published",
  },
  {
    id: "thu-tuc-369083-dvc",
    title: "Thủ tục cấp phép bay đối với UAV / phương tiện bay siêu nhẹ",
    docNumber: "TTHC-369083",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=369083",
    abstract: "Dịch vụ công trực tuyến nộp hồ sơ xin cấp phép bay.",
    category: "Thủ tục cấp phép bay",
    status: "published",
  },
  {
    id: "thu-tuc-424492-dvc",
    title: "Thủ tục cấp Giấy phép điều khiển tàu bay không người lái",
    docNumber: "TTHC-424492",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://thutuc.dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=424492",
    abstract: "Thủ tục hành chính cấp bằng / chứng chỉ điều khiển UAV.",
    category: "Giấy phép điều khiển",
    status: "published",
  },
  {
    id: "thu-tuc-424445-dvc",
    title: "Thủ tục cấp đổi, cấp lại Giấy phép điều khiển UAV",
    docNumber: "TTHC-424445",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=424445",
    abstract: "Dịch vụ công cấp đổi hoặc cấp lại bằng lái drone khi hết hạn hoặc mất.",
    category: "Giấy phép điều khiển",
    status: "published",
  },
  {
    id: "thu-tuc-424400-dvc",
    title: "Thủ tục cấp đổi, cấp lại Giấy chứng nhận đủ điều kiện kinh doanh UAV",
    docNumber: "TTHC-424400",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://vpcp.dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=424400",
    abstract: "Đăng ký chứng nhận kinh doanh thiết bị bay không người lái.",
    category: "Doanh nghiệp / sản xuất",
    status: "published",
  },
  {
    id: "thu-tuc-1014683-dvc",
    title: "Thủ tục cấp Giấy chứng nhận đủ điều kiện cơ sở nghiên cứu, chế tạo, sản xuất, sửa chữa, thử nghiệm UAV",
    docNumber: "TTHC-1.014683",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://vpcp.dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.014683",
    abstract: "Chứng nhận cấp phép cho các cơ sở R&D, chế tạo và thử nghiệm drone tại Việt Nam.",
    category: "Doanh nghiệp / sản xuất",
    status: "published",
  },
  {
    id: "thu-tuc-424493-dvc",
    title: "Thủ tục chấp thuận điều kiện nhập khẩu tàu bay không người lái",
    docNumber: "TTHC-424493",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=424493",
    abstract: "Thủ tục kiểm tra và cho phép nhập khẩu thiết bị drone.",
    category: "Nhập khẩu",
    status: "published",
  },
  {
    id: "thu-tuc-1008278-dvc",
    title: "Thủ tục cấp phép cơ sở thử nghiệm tàu bay không người lái và thiết bị",
    docNumber: "TTHC-1.008278",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-chi-tiet-thu-tuc-nganh-doc.html?ma_thu_tuc=1.008278",
    abstract: "Quy trình xin cấp phép sân thử và cơ sở thử nghiệm thiết bị bay.",
    category: "Cơ sở thử nghiệm",
    status: "published",
  },
  {
    id: "thu-tuc-227137-dvc",
    title: "Thủ tục cấp đổi giấy phép cơ sở thiết kế, sản xuất, sửa chữa, bảo dưỡng UAV",
    docNumber: "TTHC-227137",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=227137",
    abstract: "Cấp đổi phép hoạt động cơ sở sản xuất và bảo dưỡng drone.",
    category: "Cơ sở thử nghiệm",
    status: "published",
  },
  {
    id: "thu-tuc-227157-dvc",
    title: "Thủ tục cấp lại giấy phép cơ sở thiết kế, sản xuất, sửa chữa, bảo dưỡng UAV",
    docNumber: "TTHC-227157",
    agency: "Cổng Dịch vụ công Quốc gia",
    url: "https://dichvucong.gov.vn/p/home/dvc-tthc-thu-tuc-hanh-chinh-chi-tiet.html?ma_thu_tuc=227157",
    abstract: "Cấp lại phép cho doanh nghiệp thiết kế, sản xuất drone.",
    category: "Cơ sở thử nghiệm",
    status: "published",
  },
  {
    id: "he-thong-van-ban-chinhphu",
    title: "Hệ thống văn bản quy phạm pháp luật – Cổng Thông tin điện tử Chính phủ",
    docNumber: "Chính phủ Whitelist Root",
    agency: "Chính phủ",
    url: "https://vanban.chinhphu.vn/he-thong-van-ban?classid=1&mode=1",
    abstract: "Nguồn tổng tra cứu văn bản pháp luật chính thức của Chính phủ.",
    category: "Nguồn tổng rà soát",
    status: "published",
  }
];
